// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfWtAFpv71AayK2KJmo9ZgsyHB2utsewo',
    appId: '1:274709361709:web:bb57d2f8ae5c4b161a34a4',
    messagingSenderId: '274709361709',
    projectId: 'e-commerce010',
    authDomain: 'e-commerce010.firebaseapp.com',
    storageBucket: 'e-commerce010.firebasestorage.app',
    measurementId: 'G-38YG3C31JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCLwOoKIaQeaakXwzjpMdVTyQSFmGg5g',
    appId: '1:274709361709:android:e12f756b816b30391a34a4',
    messagingSenderId: '274709361709',
    projectId: 'e-commerce010',
    storageBucket: 'e-commerce010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7fvXNvODfeojT2lNPyCrIPolwfphmeI',
    appId: '1:274709361709:ios:19292903bb7ce2851a34a4',
    messagingSenderId: '274709361709',
    projectId: 'e-commerce010',
    storageBucket: 'e-commerce010.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7fvXNvODfeojT2lNPyCrIPolwfphmeI',
    appId: '1:274709361709:ios:19292903bb7ce2851a34a4',
    messagingSenderId: '274709361709',
    projectId: 'e-commerce010',
    storageBucket: 'e-commerce010.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfWtAFpv71AayK2KJmo9ZgsyHB2utsewo',
    appId: '1:274709361709:web:72dca201d662dea21a34a4',
    messagingSenderId: '274709361709',
    projectId: 'e-commerce010',
    authDomain: 'e-commerce010.firebaseapp.com',
    storageBucket: 'e-commerce010.firebasestorage.app',
    measurementId: 'G-01742JDGGL',
  );
}
